CLASS ZCC4AZTEST_CHECK_CONSTANT_IF1 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCC4AZTEST_CHECK_CONSTANT_IF1 IMPLEMENTATION.
ENDCLASS.
